### PR TITLE
TE-10379 Added PHP8.1 to CI

### PR DESCRIPTION
**Pull request by dmytro-dymarchuk**

### CODE REVIEW

**Comment by dereuromark** [comment]
Needs to be done on existing pr https://github.com/spryker-eco/payone/pull/76
We can postpone this for until after release

**Comment by dereuromark** [comment]
@michbeck Please see https://github.com/spryker-eco/payone/runs/4583835752?check_suite_focus=true#step:12:43

**Comment by dereuromark** [comment]
Is this on propel side?
```
In ClassTools.php line 29:
                                                                               
  strrpos(): Passing null to parameter #1 ($haystack) of type string is depre  
  cated   
```

**Comment by dmytro-dymarchuk** [comment]
> Is this on propel side?

Yes. The full name of the class is `\Propel\Generator\Builder\Om\ClassTools`. And as I see this issue can not be found by phpstan since param looks like string for phpstan.

```
/**
     * Gets just classname, given a dot-path to class.
     *
     * @param string $qualifiedName
     *
     * @return string
     */
    public static function classname($qualifiedName)
    {
        if (false !== $pos = strrpos($qualifiedName, '.')) {
            return substr($qualifiedName, $pos + 1); // start just after '.'
        } elseif (false !== $pos = strrpos($qualifiedName, '\\')) {
            return substr($qualifiedName, $pos + 1);
        } else {
            return $qualifiedName;  // there is no '.' in the qualified name
        }
    }

**Comment by dmytro-dymarchuk** [comment]
But as I see this has been already fixed. https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Builder/Om/ClassTools.php#L27

**Comment by dereuromark** [comment]
Best to make PR against the open PR I linked instead of outdated master.

**Comment by dereuromark** [comment]
Whats missing?

**Comment by dmytro-dymarchuk** [comment]
> Whats missing?

This PR is outdated and has closed target branch and should be closed as well. I created new PR https://github.com/spryker-eco/payone/pull/80. There is the same issue with https://github.com/spryker-eco/payone/pull/77#issuecomment-999634196

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/spryker-eco/payone/pull/80

**Pull request closed without merging**
