### PR TITLE
APPS-138: Payment API improvements

### PR DESCRIPTION
**Pull request by olehnovatskyi-spryker**
- Developer(s): @olehnovatskyi-spryker

- Release Group: https://release.spryker.com/release-groups/view/3493

- Ticket: https://spryker.atlassian.net/browse/APPS-138

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Payone      | minor           |CheckoutExtension                       |
-----------------------------------------

##### Change log

Improvements

- Introduced `PayoneFacade::orderPostSave()` to check log redirect and authorization redirect in one function call.
- Introduced `PayoneFacade::saveOrderPayment()`.
- Introduced `PayoneCheckoutDoSaveOrderPlugin` to save **Payone** payment.
- Introduced `PayoneCheckoutPostSavePlugin` to execute additional logic after saving order data to DB.
- Introduced `PayoneCheckoutPreConditionPlugin` to validate the quote before saving the order to DB.

Deprecations
- Deprecated `PayoneFacadeInterface::saveOrder()`.
- Deprecated `PayoneFacadeInterface::postSaveHook()`.
- Deprecated `PayoneFacadeInterface::executeCheckoutPostSaveHook()`.
- Deprecated `PayoneCheckoutPostSaveHookPlugin`.
- Deprecated `PayonePostSaveHookPlugin`.
- Deprecated `PayonePreCheckPlugin`.
- Deprecated `PayoneSaveOrderPlugin`.

### CODE REVIEW

**Comment by dereuromark** [comment]
Can you resolve the conflict using Yours please.

**Comment by dereuromark** [comment]
Please also see https://github.com/spryker-eco/payone/runs/2609558229?check_suite_focus=true

**Comment by dereuromark** [comment]
I dont see CI result now, though. Did you resolve the ci.yml?

**Comment by olehnovatskyi-spryker** [comment]
Job 'Validation': results of next steps after failed one
composer update --prefer-lowest --prefer-dist --no-interaction --profile -vvv
Screenshot from 2021-05-20 18-03-09

**Review by matweew — APPROVED** [review]

**Pull request merged**
